CREATE DATABASE IF NOT EXISTS BIBLIOTECA_SAEP_DB;
USE BIBLIOTECA_SAEP_DB;

CREATE TABLE IF NOT EXISTS USUARIOS(
	USU_ID 		INT AUTO_INCREMENT PRIMARY KEY,
    USU_NOME 	VARCHAR(255) NOT NULL,
    USU_EMAIL 	VARCHAR(255) NOT NULL,
    USU_SENHA 	VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUTOS(
	PRO_ID 				INT AUTO_INCREMENT PRIMARY KEY,
    PRO_NOME 			VARCHAR(255) NOT NULL,
    PRO_ESTOQUE_MINIMO 	INT NOT NULL
);

CREATE TABLE IF NOT EXISTS ESTOQUES(
	EST_ID 			INT AUTO_INCREMENT PRIMARY KEY,
    EST_QUANTIDADE	INT NOT NULL,
    FK_PRO_ID 		INT NOT NULL,
    FOREIGN KEY (FK_PRO_ID) REFERENCES PRODUTOS(PRO_ID) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS MOVIMENTACOES(
	MOV_ID 			INT AUTO_INCREMENT PRIMARY KEY,
    MOV_TIPO 		ENUM('ENTRADA', 'SAIDA') NOT NULL,
    MOV_QUANTIDADE	INT NOT NULL,
    MOV_DATA_HORA 	DATETIME NOT NULL,
    FK_PRO_ID 		INT NOT NULL,
    FK_USU_ID 		INT NOT NULL,
    FOREIGN KEY (FK_PRO_ID) REFERENCES PRODUTOS(PRO_ID) ON DELETE CASCADE,
    FOREIGN KEY (FK_USU_ID) REFERENCES USUARIOS(USU_ID) ON DELETE CASCADE
);

INSERT INTO USUARIOS (USU_NOME, USU_EMAIL, USU_SENHA) VALUES
('Ana Souza', 'ana@biblioteca.com', '123456'),
('Carlos Lima', 'carlos@biblioteca.com', '123456'),
('Mariana Oliveira', 'mariana@biblioteca.com', '123456');

INSERT INTO PRODUTOS (PRO_NOME, PRO_ESTOQUE_MINIMO) VALUES
('Dom Casmurro', 3),
('O Pequeno Príncipe', 5),
('1984', 4);

INSERT INTO ESTOQUES (EST_QUANTIDADE, FK_PRO_ID) VALUES
(10, 1),
(8, 2),
(6, 3);

INSERT INTO MOVIMENTACOES (
    MOV_TIPO,
    MOV_QUANTIDADE,
    MOV_DATA_HORA,
    FK_PRO_ID,
    FK_USU_ID
) VALUES
('ENTRADA', 10, '2026-08-01 08:30:00', 1, 1),
('SAIDA', 2, '2026-08-05 14:20:00', 2, 2),
('ENTRADA', 6, '2026-08-10 10:15:00', 3, 3);